apiVersion: v1
kind: Service
metadata:
  name: {{ template "socrates.name" . }}-api
  labels:
    app: {{ template "socrates.name" . }}-api
    chart: {{ template "socrates.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.api.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}      
{{- end }} 
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "socrates.name" . }}-api
    release: {{ .Release.Name }}
  sessionAffinity: ClientIP